### ISSUE TITLE
nmod_mat_nullspace regression in flint 3.x

### ISSUE THREAD

**Issue by wjyoumans** [flintlib/flint#1434] opened 2023-10-03 03:44 UTC
I'm finding that `nmod_mat_nullspace` has worse performance on full rank (or close to it) matrices in flint 3.x compared to 2.x. 

I made a quick example that should work to demonstrate. This creates a 5000x5000 full rank matrix mod 929 and computes the nullspace.

On flint 3.x the output is:
```
flint version: 3.0.0-alpha1
Startup time: 0.02823
Nullspace time: 27.3402
```

On flint 2.x:
```
flint version: 2.9.0
Startup time: 0.030741
Nullspace time: 8.12024
```

So ~27 seconds with flint 3.x, ~8 seconds with 2.x. With openblas enabled it is ~3 seconds in flint 2.x, and I didn't test flint 3.x with openblas. I had the same results with different random seeds.

The test code:
```
int main() {
  std::cout << "flint version: " << FLINT_VERSION << '\n';
  int n = 5000;
  int q = 929;
  
  flint_rand_t state;
  flint_randinit(state);

  nmod_mat_t rand;
  nmod_mat_init(rand, n, n, q);
  
  clock_t begin = clock();
  nmod_mat_randrank(rand, state, n);
  clock_t end = clock();
  double t = (double)(end - begin)/CLOCKS_PER_SEC;
  std::cout << "Startup time: " << t << '\n';

  nmod_mat_t res;
  nmod_mat_init(res, n, n, q);
  
  begin = clock();
  nmod_mat_nullspace(res, rand);
  end = clock();
  t = (double)(end - begin)/CLOCKS_PER_SEC;
  std::cout << "Nullspace time: " << t << '\n';

  nmod_mat_clear(res);
  nmod_mat_clear(rand);
  flint_randclear(state);
  return 0;
}
```

**Comment by fredrik-johansson** [comment] 2023-10-03 06:32
I'm unable to reproduce:

```
flint version: 2.10.0
Startup time: 0.073567
Nullspace time: 6.66582
```

```
flint version: 3.0.0-dev
Startup time: 0.073971
Nullspace time: 6.60191
```

**Comment by vneiger** [comment] 2023-10-09 09:59
Unable to exactly reproduce as such, but here is some insight still as to what may be the issue.

I compiled flint with blas enabled, using the BLIS implementation. Compiling the provided code with `-lblis` and without it does not yield the same behaviour (and seems to give differences of timings similar to what was reported in this issue).

```
~$ g++ main.cpp  -lflint -lgmp -lblis
~$ time ./a.out
flint version: 3.0.0-dev
Startup time: 0.916485
Nullspace time: 9.06531

real    0m9,226s
user    0m8,938s
sys     0m1,080s

~$ g++ main.cpp  -lflint -lgmp
~$ time ./a.out
flint version: 3.0.0-dev
Startup time: 0.914424
Nullspace time: 21.2946

real    0m8,923s
user    0m13,104s
sys     0m9,142s
```
Running `htop` shows that when compiling without `-lblis`, several cores are used (4 core machine). My guess is that in this case, it is another package which is called, in my case the Debian `libopenblas0` which is packaged with multiple thread support by default. And the following test would tend to confirm this:

````
~$ time OMP_NUM_THREADS=1 ./a.out
flint version: 3.0.0-dev
Startup time: 0.113656
Nullspace time: 8.9288

real    0m9,067s
user    0m8,770s
sys     0m0,296s
```

@wjyoumans  Could you investigate to see if your issue comes from a similar source?

**Comment by vneiger** [comment] 2023-10-09 10:09
Some more information. Nullspace uses `rref`, which calls an LU decomposition, which eventually uses matrix multiplication for large matrices (`nmod_mat_mul` or `nmod_mat_submul`). If I do similar measures with multiplication (code below):
```
~$ g++ main_mul.cpp  -lflint -lgmp -lblis
~$ time ./a.out
flint version: 2.9.0
Startup time: 0.213228
Nullspace time: 5.28984

real    0m5,539s
user    0m5,254s
sys     0m0,284s

~$ g++ main_mul.cpp  -lflint -lgmp
~$ time OMP_NUM_THREADS=1 ./a.out
flint version: 2.9.0
Startup time: 0.202828
Nullspace time: 4.68829

real    0m4,923s
user    0m4,602s
sys     0m0,320s

~$ time ./a.out
flint version: 2.9.0
Startup time: 0.92763
Nullspace time: 12.2038

real    0m2,177s
user    0m11,022s
sys     0m2,147s
```

(forget the `nullspace` word... this is from copy-pasting; this is actually 5000 x 5000 `nmod_mat_mul`)

Is this behaviour wanted? It seems this could create confusion for the user; one may expect single-threaded computations unless explicitly asking for multiple threads (?).


```
#include <iostream>
#include <flint/flint.h>
#include <flint/flintxx.h>
#include <flint/nmod_mat.h>
using namespace std;

int main() {
  std::cout << "flint version: " << FLINT_VERSION << '\n';
  int n = 5000;
  int q = 929;
  
  flint_rand_t state;
  flint_randinit(state);

  nmod_mat_t rand;
  nmod_mat_init(rand, n, n, q);
  
  clock_t begin = clock();
  nmod_mat_randrank(rand, state, n);
  clock_t end = clock();
  double t = (double)(end - begin)/CLOCKS_PER_SEC;
  std::cout << "Startup time: " << t << '\n';

  nmod_mat_t res;
  nmod_mat_init(res, n, n, q);
  
  begin = clock();
  nmod_mat_nullspace(res, rand);
  end = clock();
  t = (double)(end - begin)/CLOCKS_PER_SEC;
  std::cout << "Nullspace time: " << t << '\n';

  nmod_mat_clear(res);
  nmod_mat_clear(rand);
  flint_randclear(state);
  return 0;
}
```

**Comment by wjyoumans** [comment] 2023-10-13 16:06
I'm having trouble compiling the benchmark using specific flint libraries right now. There is one in `/usr/lib` (I don't know why) which it sometimes defaults to despite me giving the path of the specific library I want to use (2.9, 2.10, 3.0 etc) that is making it difficult. (This time around I am confirming linked libraries with `ldd`, which I didn't before).

@vneiger I did not compile any examples with blas and I specifically built each flint version without it to be sure everything was multithreaded, but I see `/usr/lib/libflint.so` is compiled with cblas, so it may have been tainting the run times I showed. The odd thing is building the benchmark with this version gives me the ~27 second runtime...

I have to set up flint on a fresh system anyway so I will retry the benchmarks and report back (while confirming they are linked to the versions I expected with ldd).

**Comment by wjyoumans** [comment] 2023-10-13 20:44
OK it seems to have been the system installed version of flint messing things up. The system installed version was built with BLAS, which used multithreading by default giving me a slower time. I was linking to this version accidentally, when I thought I was linking to single threaded flint 3.x.

When I linked to flint 2.9 without BLAS it was faster, and I mistook this for an issue between the flint versions. See the timings I get now below, where I made sure the correct versions of flint are being used. 

Basically I was comparing flint 2.9 with and without multithreading, not single-threaded flint 2.x and 3.x like I thought. So @vneiger was right, it was confusion around the default multi threading.

I think this can be closed, thanks for the help.

```
$ g++ bench_nullspace.cpp -o bench -L$FLINT2_DIR -lflint -I$FLINT2_DIR  -L$PREFIX/lib -lgmp -lblis

$ time ./bench
flint version: 2.9.0
Startup time: 1.01138
Nullspace time: 19.1741

real	0m3.765s
user	0m11.993s
sys	0m8.247s

$ time OMP_NUM_THREADS=1 ./bench
flint version: 2.9.0
Startup time: 0.077556
Nullspace time: 3.80308

real	0m3.914s
user	0m3.521s
sys	0m0.393s
```

```
$ g++ bench_nullspace.cpp -o bench -L$FLINT3_DIR -lflint -I$FLINT3_DIR/src  -L$PREFIX/lib -lgmp -lblis

$ time ./bench
flint version: 3.0.0-alpha1
Startup time: 1.00883
Nullspace time: 18.8994

real	0m3.765s
user	0m11.709s
sys	0m8.256s

$ time OMP_NUM_THREADS=1 ./bench
flint version: 3.0.0-alpha1
Startup time: 0.0783
Nullspace time: 3.86451

real	0m3.977s
user	0m3.579s
sys	0m0.396s
```

**Comment by vneiger** [comment] 2023-10-13 20:54
Thank you @wjyoumans  for re-analyzing this carefully. I will then close this issue.

[There still remains the above-mentioned issue about "-lopenblas" being added during configuration even when another BLAS-providing library was specified at configure time (thanks for helping to detect this), but I will open another issue about this, since this seems independent from the issue here which was initially about an observed performance regression.]

**Closed by vneiger** 2023-10-13 20:54 UTC
Labels: performance
